dist: bionic
sudo: required # apt-get done in before_install.sh
language: minimal

# Only build master or PRs merging into master
branches:
  only:
  - master

# List of configurations to check
matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
          - valgrind
# Build phases
before_install:
  - source ./scripts/travis/before_install.sh
# install: # dependencies
#   - ./scripts/travis/install.sh
script:
  - run_script configure
  - run_script compile
  - run_script test
